### ISSUE TITLE
Expose orient of an axis

### ISSUE THREAD

**Issue by c-dante** [d3/d3-axis#16]
Without having the orient set, if I'm passed an anonymous axis object, I cannot inspect to see what orientation it is at.

If I wanted to transform containing elements based on orientation, there's no way to do that.

Added a PR for this #17.

**Comment by mbostock** [comment]
I don’t think it’s a good idea to expose an enumeration of axis orientations. There might be other orientations in the future, such as for polar coordinates. And it feels icky, especially if the orientation is defined as a string.

By analogy, consider scales: there’s no *scale*.type method to distinguish different types of scales such as d3.scaleLinear and d3.scaleOrdinal. Occasionally you need to distinguish scale types; for example, d3-axis tests for the presence of [*scale*.bandwidth](https://github.com/d3/d3-axis/blob/master/src/axis.js#L48) to shift ticks to the middle of each band for [band scales](https://github.com/d3/d3-scale/blob/master/README.md#band-scales). But as that case demonstrates, it’s better to test for a specific feature (bandwidth) than to enumerate the scale types explicitly. Extending the analogy, when developing on the web, it’s better to test whether the current browser supports a feature than to write code that checks the user-agent.

It’d be nice, maybe, if you could use `instanceof` to test whether something is a particular type of scale, but alas that does not play nice with D3’s use of functions-as-objects, where a scale (like an axis) is both a function and an object. There’s no way to extend Function in JavaScript. (Actually that’s not totally true because you can say `class Foo extends Function {}`, but I think that requires using the Function constructor—there’s no way to extend a closure defined by a function expression, as far as I know.) So you can’t say `x instanceof d3.scaleLinear`, either, although that is supported for D3 classes that do not extend function, such as d3.selection.

I can’t see the code you’re writing, but it might be better for you to expose four of your own constructors, and then instantiate the axis internally. That way you’re in control of how the axis gets instantiated, and you know what orientation it is, and there’s no possibility of receiving an axis of an unsupported (or unknown) orientation.

**Comment by c-dante** [comment]
I was considering either wrapping the axis construction or just adding a property to it (such as "type" or otherwise) -- doesn't need to be a string or the like. That's probably the avenue I'll take moving forward.
