### ISSUE TITLE
Axis labels are not removed from the DOM

### ISSUE THREAD

**Issue by moroshko** [d3/d3-axis#23]
I'm implementing a chart that has a sliding x axis. 

I noticed that the axis labels that slide out of the chart are not removed from the DOM.

Why? How could I fix that to prevent the DOM growing indefinitely?

[Demo](http://codepen.io/moroshko/pen/ygavbw?editors=0010)

**Comment by curran** [comment]
If you change the following line

```js
    .on('end', animate);
```

to

```js
    .on('end', function (){ setTimeout(animate); });
```

, then the number of elements remains 10 (`10` gets printed again and again).

Here's an [updated demo](http://codepen.io/anon/pen/NdRyLE?editors=0010).

I made this change purely on intuition, I don't fully understand *why* this fixes the problem. Probably something to do with asynchronous control flow and how the `exit()` part of the axes is implemented.

**Comment by mbostock** [comment]
The problem is that when the *end* event for the parent G element is dispatched, the axis has not yet removed the old ticks. The ticks are removed by [*transition*.remove](https://github.com/d3/d3-transition/blob/master/README.md#transition_remove), which listens for the [*end* event](https://github.com/d3/d3-transition/blob/master/src/transition/remove.js) on the tick elements. The *end* event for the G element is dispatched prior to the *end* event for the tick elements, so you are starting a new transition that interrupts the old one before the axis has a chance to remove the old ticks.

If you want a real-time axis, you probably don’t want transitions. Instead, use d3.timer and redraw the axis with every tick.

```js
var x = d3.scaleTime()
    .range([0, width]);

var xAxis = d3.axisBottom(x);

var xG = svg.append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")")
    .call(xAxis);

d3.timer(function() {
  var now = Date.now();
  x.domain([now - 10 * 6000, now]);
  xG.call(xAxis);
});
```

If you want an infinitely-chaining transition, then either you should wait until after the *end* event to start your new transition (such as by using d3.timeout), or you should [d3.active](https://github.com/d3/d3-transition/blob/master/README.md#active) and [*transition*.transition](https://github.com/d3/d3-transition/blob/master/README.md#transition_transition) to schedule a [chained transition](http://bl.ocks.org/mbostock/70d5541b547cc222aa02) that will not interrupt your current transition. That would look like this:

```js
var x = d3.scaleTime()
    .domain(interval(0))
    .range([0, width]);

var xAxis = d3.axisBottom(x);

svg.append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")")
    .call(xAxis)
  .transition()
    .duration(1000)
    .ease(d3.easeLinear)
    .on("start", animate);

function animate() {
  x.domain(interval(1000));

  d3.active(this)
      .call(xAxis)
    .transition()
      .on("start", animate);
}

function interval(offset) {
  var now = Date.now() + offset;
  return [now - 10 * 6000, now];
}
```

http://bl.ocks.org/mbostock/e82068fbaf4f2d75549c4a480b28f643

The main thing I don’t like about the latter approach is that if you background the tab, when you return to the foreground, it will do a 1-second linear transition to the current time interval, so the axis will slide very quickly as it returns to the current time. It’d probably be better to just draw the axis in realtime as under the first approach.

**Comment by moroshko** [comment]
Thanks Mike for such a detailed response!
