### ISSUE TITLE
Can any scale be used?

### ISSUE THREAD

**Issue by Frikki** [d3/d3-axis#43]
Can I, for example, use a `ScaleOrdinal` where the range isn't a number list? I'm particularly concerned about this code: https://github.com/d3/d3-axis/blob/master/src/axis.js#L51

**Comment by mbostock** [comment]
The scale must be a positional scale to be displayed as an access, so the range must be numeric. What do you have if you don’t have a numeric range? Perhaps you’re looking for a [legend](http://d3-legend.susielu.com/)?

Typically a scaleBand or scalePoint would be used instead of scaleOrdinal, but you can use a scaleOrdinal as long as the range is numeric and in either ascending or descending order.

https://bl.ocks.org/mbostock/268bb5fb6e1025b60f01a35311ed798b
