### ISSUE TITLE
Date boundary issue for months with 31 days

### ISSUE THREAD

**Issue by thecakelin** [d3/d3-axis#55]
![image](https://user-images.githubusercontent.com/8183912/54141583-f5b67480-43f3-11e9-88ee-2d39fcad7320.png)

For months with 31 days, it is affecting the scale of the axis. This doesn't happen with 30 days or 28. 

React and typescript, versions:

    "d3": "^5.7.0"

    "@types/d3": "^5.5.0",
    "@types/d3-array": "^1.2.4",
    "@types/d3-shape": "^1.2.2",

**Comment by mbostock** [comment]
A good bug report should **isolate specific methods** that exhibit unexpected behavior and define precisely how expectations were violated. What did you expect the method or methods to do, and how did the observed behavior differ? By isolating the issue, you assist the investigation.

When reporting an issue, please include a link to a live example, preferably as an [Observable notebook](https://observablehq.com) or as a pull request in the [appropriate repository](https://github.com/d3) with tests. You should demonstrate that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md) using the minimum amount of code.

Non-actionable bugs may be closed until you provide additional information. If you can’t isolate the bug further, please reply and ask for help. However, please be patient: open-source maintainers have many competing responsibilities—fixing other bugs, answering questions, developing features, writing documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
