### ISSUE TITLE
`axis.tickValues` could also return `values`? 

### ISSUE THREAD

**Issue by zfrenchee** [d3/d3-axis#57]
> `axis.tickValues([values])`
> 
> ... If values is not specified, returns the current tick values, which defaults to null. ...

I would have expected, that once an axis is drawn (and has called `scale.ticks()`) calling `axis.tickValues()` would return me the cached [`continuous.ticks`](https://github.com/d3/d3-scale/blob/master/README.md#continuous_ticks). However, since I did not previously set `axis.tickValues(a_value)`,  `axis.tickValues()` returns null. (I'm assuming that calling `continuous.ticks()` requires computation.)

I think this would involve changing this line to set tickValues as well as values

https://github.com/d3/d3-axis/blob/da24fba38bb895a3a7ed9f3fdddda1a545eec97e/src/axis.js#L48

Or expose a new method to get the current values. In the meantime I'll just call `continuous.ticks`.

---

By the way, why doesn't [`continuous.ticks`](https://github.com/d3/d3-scale/blob/master/README.md#continuous_ticks) have a `<>` which links to some line of code in the source?

**Comment by mbostock** [comment]
It could compute the tick values, but then you’d have no way of knowing whether the axis is configured to use the scale to compute the ticks, or whether the tick values are explicitly specified through *axis*.tickValues, and similarly there’d be no way to copy the settings from one axis to another.

There’s no link from *continuous*.ticks to the source because it’s an interface with multiple implementations. And I didn’t want to duplicate the methods for every scale type…

https://github.com/d3/d3-scale/blob/master/src/linear.js
https://github.com/d3/d3-scale/blob/master/src/log.js

**Comment by zfrenchee** [comment]
@mbostock that's fair. So every time I want ticks from a scale for a given axis, I need to recompute the ticks? There's no method to access the cached ones?

**Comment by mbostock** [comment]
Correct.
