### ISSUE TITLE
Ability to set axis ticks count when using axis `tickFormat`  function

### ISSUE THREAD

**Issue by KaroMourad** [d3/d3-axis#86]
I have the problem when setting the `axis.ticks(tickCount).tickFormat(cb)`.

The `tickFormat` function resets the ticks count and shows all tick values but instead, it would be better if we could add `tickCount` argument in `tickFormat`  callback function or as a second argument. 

d3 version 7.4.4

**Comment by KaroMourad** [comment]
the main problem comes when I want to cut the axis ticks values if the length of the tick values is too long

**Comment by Fil** [comment]
Can you clarify what the issue is? I'm not able to reproduce. With the following:

```
d3.axisBottom(d3.scaleLinear([0, 1], [10, 200])).ticks(3).tickFormat((d) => d)
```

I'm still getting 3 ticks.

**Comment by KaroMourad** [comment]
@Fil thank you for the quick response.
The issue comes when the axis scale is logarithmic, for a linear scale it works correctly.

**Comment by KaroMourad** [comment]
@Fil , here is the [link](https://codepen.io/karomourad/pen/dydzEJw?editors=0010)
There is the `tickFormat` function commented, please  uncomment and check the results, tick count is 7 instead of 5

**Comment by Fil** [comment]
Ah yes, that's expected, for two reasons:
1. on _any_ scale, the number you pass to the ticks() method is only indicative; the axis tries to find a useful number of ticks that's close to what you're asking, while also finding "nice" ticks (multiples of 2, 5, 10).
2. log scales have a logic that is even more complex: https://github.com/d3/d3-scale/blob/main/src/log.js#L70, because we want the tick values to be readable and meaningful. We can't show the cube root of 10—it would be meaningful, but not readable.
